  query:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Start Docker services
        run: docker-compose up -d

      - name: Wait for services to be ready
        run: sleep 10  # Ensures containers are ready

      - name: Populate Database Before Queries
        run: |
          curl -X POST "http://localhost:5001/stocks" -H "Content-Type: application/json" -d '{"name": "Apple Inc.", "symbol": "AAPL", "purchase price": 183.63, "purchase date": "22-02-2024", "shares": 19}'
          curl -X POST "http://localhost:5001/stocks" -H "Content-Type: application/json" -d '{"name": "Alphabet Inc.", "symbol": "GOOG", "purchase price": 140.12, "purchase date": "18-06-2024", "shares": 14}'

      - name: Execute queries
        run: |
          touch response.txt
          while IFS= read -r line; do
            SERVICE=$(echo $line | cut -d: -f1)
            QUERY=$(echo $line | cut -d: -f2)
            RESPONSE=$(curl -s "http://localhost:5001/$SERVICE?$QUERY")
            echo -e "query: $line\nresponse: $RESPONSE\n" >> response.txt
          done < query.txt

      - name: Upload response file
        uses: actions/upload-artifact@v4
        with:
          name: query-response
          path: response.txt
